"use client";

import { useState } from "react";
import type { Lens } from "@/domain/types";
import type { Briefing, BriefingAction } from "@/domain/synthesis/types";

const PRIORITY_STYLE: Record<BriefingAction["priority"], string> = {
  now: "bg-high/10 text-high",
  soon: "bg-medium/10 text-medium",
  watch: "bg-low/10 text-low",
};

const PRIORITY_LABEL: Record<BriefingAction["priority"], string> = {
  now: "Do now",
  soon: "Soon",
  watch: "Watch",
};

export function BriefingPanel({
  lens,
  configured,
}: {
  lens: Lens;
  configured: boolean;
}) {
  const [profile, setProfile] = useState("");
  const [loading, setLoading] = useState(false);
  const [briefing, setBriefing] = useState<Briefing | null>(null);
  const [error, setError] = useState<string | null>(null);

  async function generate() {
    setLoading(true);
    setError(null);
    setBriefing(null);
    try {
      const res = await fetch("/api/briefing", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ lens, profile }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error ?? "Request failed");
      setBriefing(data.briefing as Briefing);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Something went wrong");
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="mb-6 rounded-xl border border-borderStrong bg-gradient-to-b from-white to-surfaceAlt p-5 shadow-card">
      <div className="flex items-start justify-between gap-3">
        <div>
          <h3 className="flex items-center gap-2 text-base font-semibold text-ink">
            <span>✦</span> Your &ldquo;Do now&rdquo; briefing
          </h3>
          <p className="mt-1 text-xs text-muted">
            AI-synthesized from the active insights — deduped, prioritized, and
            tailored to your situation.
          </p>
        </div>
      </div>

      {!configured ? (
        <p className="mt-4 rounded-lg border border-border bg-white p-3 text-xs text-muted">
          Synthesis is off. Set <code className="font-mono">ANTHROPIC_API_KEY</code>{" "}
          to enable a tailored, prioritized briefing generated by Claude.
        </p>
      ) : (
        <>
          <div className="mt-4 flex flex-col gap-2 sm:flex-row">
            <input
              value={profile}
              onChange={(e) => setProfile(e.target.value)}
              placeholder={
                lens === "business"
                  ? "Optional: your business, e.g. 'B2B SaaS, pre-seed, US'"
                  : "Optional: your situation, e.g. '35, saving for a house, has a mortgage'"
              }
              className="flex-1 rounded-lg border border-border bg-white px-3 py-2 text-sm text-ink outline-none placeholder:text-faint focus:border-borderStrong"
            />
            <button
              onClick={generate}
              disabled={loading}
              className="rounded-lg bg-ink px-4 py-2 text-sm font-medium text-white transition hover:opacity-90 disabled:opacity-50"
            >
              {loading ? "Synthesizing…" : "Generate briefing"}
            </button>
          </div>

          {error && (
            <p className="mt-3 rounded-lg bg-high/10 p-3 text-xs text-high">
              {error}
            </p>
          )}

          {briefing && (
            <div className="mt-4">
              <p className="text-sm leading-relaxed text-ink">{briefing.summary}</p>
              <ul className="mt-4 space-y-2">
                {briefing.actions.map((a, i) => (
                  <li
                    key={i}
                    className="rounded-lg border border-border bg-white p-3"
                  >
                    <div className="flex items-center justify-between gap-2">
                      <span className="text-sm font-semibold text-ink">
                        {a.title}
                      </span>
                      <span
                        className={`whitespace-nowrap rounded-full px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wider ${
                          PRIORITY_STYLE[a.priority]
                        }`}
                      >
                        {PRIORITY_LABEL[a.priority]}
                      </span>
                    </div>
                    <p className="mt-1 text-xs text-muted">{a.rationale}</p>
                    {a.basis.length > 0 && (
                      <div className="mt-2 flex flex-wrap gap-1">
                        {a.basis.map((b) => (
                          <span
                            key={b}
                            className="rounded border border-border bg-surface px-1.5 py-0.5 text-[10px] text-muted"
                          >
                            {b}
                          </span>
                        ))}
                      </div>
                    )}
                  </li>
                ))}
              </ul>
              <p className="mt-3 text-[10px] text-faint">
                Synthesized by Claude from curated playbooks · general tendencies,
                not financial advice.
              </p>
            </div>
          )}
        </>
      )}
    </div>
  );
}
